apiVersion: v1
kind: Pod
metadata:
  name: nginx
  Namespace: roboshop
  labels:
   name: nginx
   project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80