apiVersion: v1 
kind: Pod
metadata:
  name: multi-container
  namespace: roboshop
  labels:
    purpose: multi-container
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
  - name: almalinux
    image: almalinux:9
    command: ["sleep","1000"]
