apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    project: roboshop
    component: frontend
    environment: dev
    purpose: nodeport
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2