apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    purpose: deployement 
    project: roboshop
spec:
  replicas: 4
  selector:
    matchLabels:
      purpose: deployement
      project: roboshop
  template:
    metadata:
      labels:
        purpose: deployement
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:trixie-perl